[package]
name = "alloc-pool"
version = "0.2.11"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Cache pool for objects which are expensive for allocation."
edition = "2018"

[dependencies]
